server:
  port: 8080
  shutdown:  graceful
  tomcat:
    keep-alive-timeout: "70s"

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:///test_sellers


  lifecycle:
    timeout-per-shutdown-phase: "40s"


  jackson:
    property-naming-strategy: SNAKE_CASE
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile


management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "health,metrics,prometheus"
      path-mapping:
        metrics: "actuator/metrics"
        prometheus: "actuator/prometheus"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  server:
    port: 8001

jwt:
  secret: ${JWT_SECRET}
