logging:
  config: "classpath:logback-local.xml"

server:
  port: 8002

spring:
  datasource:
    rw:
      hikari:
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${DB_HOST}
    ro:
      hikari:
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${DB_HOST_READONLY}
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: update
        ddl-auto: none

springdoc:
  swagger-ui:
    path: /api-docs
    url: /docs/swagger.yaml
