object Dependency {
    const val targetJvmVersion = "21"
    const val kotlinVersion = "1.9.21"
    const val springBootVersion = "3.2.4"
    const val springCloudVersion = "2023.0.0"
    const val restdocsapiSpecVersion = "0.19.2"
    const val liquibaseVersion = "4.10.0"
    const val sentryVersion = "6.15.0"
    const val mySQLConnectorVersion = "8.0.32"
    const val hibernateValidatorVersion = "8.0.0.Final"
    const val kotestVersion = "5.6.1"
    const val kotestSprintExtensions = "1.1.3"
    const val mockkVersion = "1.13.5"
    const val springMockkVersion = "4.0.2"
    const val jjwtVersion = "0.11.5"
    const val coroutinesVersion = "1.7.2"
    const val mapStructVersion = "1.5.5.Final"
    const val redissonVersion = "3.25.2"
    const val openfeignVersion = "13.1"
    const val detektVersion = "1.23.4"
    const val fixtureMonkey = "1.0.13"
    const val jacocoToolVersion = "0.8.11"
    const val aspectjVersion = "1.9.21.1"
    const val awsSdkVersion = "1.12.576"
}
